FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

# copy requirements FIRST (for caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install runpod

# THEN copy rest of code
COPY . .

CMD ["python", "handler.py"]